INSERT INTO direction(director_id, movie_id) VALUES
((SELECT id FROM director WHERE name = 'Sidney Lumet'), (SELECT id FROM movie WHERE title = '12 Angry Men'))
,((SELECT id FROM director WHERE name = 'Steve McQueen'), (SELECT id FROM movie WHERE title = '12 Years a Slave'))
,((SELECT id FROM director WHERE name = 'Sam Mendes'), (SELECT id FROM movie WHERE title = '1917'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = '2001: A Space Odyssey'))
,((SELECT id FROM director WHERE name = 'Rajkumar Hirani'), (SELECT id FROM movie WHERE title = '3 Idiots'))
,((SELECT id FROM director WHERE name = 'Ron Howard'), (SELECT id FROM movie WHERE title = 'A Beautiful Mind'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'A Clockwork Orange'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'Ace in the Hole'))
,((SELECT id FROM director WHERE name = 'Chan-wook Park'), (SELECT id FROM movie WHERE title = 'The Handmaiden'))
,((SELECT id FROM director WHERE name = 'Katsuhiro Ôtomo'), (SELECT id FROM movie WHERE title = 'Akira'))
,((SELECT id FROM director WHERE name = 'Ron Clements'), (SELECT id FROM movie WHERE title = 'Aladdin'))
,((SELECT id FROM director WHERE name = 'John Musker'), (SELECT id FROM movie WHERE title = 'Aladdin'))
,((SELECT id FROM director WHERE name = 'Ridley Scott'), (SELECT id FROM movie WHERE title = 'Alien'))
,((SELECT id FROM director WHERE name = 'James Cameron'), (SELECT id FROM movie WHERE title = 'Aliens'))
,((SELECT id FROM director WHERE name = 'Joseph L. Mankiewicz'), (SELECT id FROM movie WHERE title = 'All About Eve'))
,((SELECT id FROM director WHERE name = 'Milos Forman'), (SELECT id FROM movie WHERE title = 'Amadeus'))
,((SELECT id FROM director WHERE name = 'Sam Mendes'), (SELECT id FROM movie WHERE title = 'American Beauty'))
,((SELECT id FROM director WHERE name = 'Tony Kaye'), (SELECT id FROM movie WHERE title = 'American History X'))
,((SELECT id FROM director WHERE name = 'Alejandro G. Iñárritu'), (SELECT id FROM movie WHERE title = 'Amores Perros'))
,((SELECT id FROM director WHERE name = 'Sriram Raghavan'), (SELECT id FROM movie WHERE title = 'Andhadhun'))
,((SELECT id FROM director WHERE name = 'Andrei Tarkovsky'), (SELECT id FROM movie WHERE title = 'Andrei Rublev'))
,((SELECT id FROM director WHERE name = 'Francis Ford Coppola'), (SELECT id FROM movie WHERE title = 'Apocalypse Now'))
,((SELECT id FROM director WHERE name = 'Anthony Russo'), (SELECT id FROM movie WHERE title = 'Avengers: Endgame'))
,((SELECT id FROM director WHERE name = 'Joe Russo'), (SELECT id FROM movie WHERE title = 'Avengers: Endgame'))
,((SELECT id FROM director WHERE name = 'Anthony Russo'), (SELECT id FROM movie WHERE title = 'Avengers: Infinity War'))
,((SELECT id FROM director WHERE name = 'Joe Russo'), (SELECT id FROM movie WHERE title = 'Avengers: Infinity War'))
,((SELECT id FROM director WHERE name = 'Çagan Irmak'), (SELECT id FROM movie WHERE title = 'My Father and My Son'))
,((SELECT id FROM director WHERE name = 'Majid Majidi'), (SELECT id FROM movie WHERE title = 'Children of Heaven'))
,((SELECT id FROM director WHERE name = 'Robert Zemeckis'), (SELECT id FROM movie WHERE title = 'Back to the Future'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'Barry Lyndon'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'Batman Begins'))
,((SELECT id FROM director WHERE name = 'Richard Linklater'), (SELECT id FROM movie WHERE title = 'Before Sunrise'))
,((SELECT id FROM director WHERE name = 'Richard Linklater'), (SELECT id FROM movie WHERE title = 'Before Sunset'))
,((SELECT id FROM director WHERE name = 'William Wyler'), (SELECT id FROM movie WHERE title = 'Ben-Hur'))
,((SELECT id FROM director WHERE name = 'Ridley Scott'), (SELECT id FROM movie WHERE title = 'Blade Runner'))
,((SELECT id FROM director WHERE name = 'Mel Gibson'), (SELECT id FROM movie WHERE title = 'Braveheart'))
,((SELECT id FROM director WHERE name = 'George Roy Hill'), (SELECT id FROM movie WHERE title = 'Butch Cassidy and the Sundance Kid'))
,((SELECT id FROM director WHERE name = 'Sergio Leone'), (SELECT id FROM movie WHERE title = 'Once Upon a Time in the West'))
,((SELECT id FROM director WHERE name = 'Nadine Labaki'), (SELECT id FROM movie WHERE title = 'Capernaum'))
,((SELECT id FROM director WHERE name = 'Michael Curtiz'), (SELECT id FROM movie WHERE title = 'Casablanca'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'Casino'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Catch Me If You Can'))
,((SELECT id FROM director WHERE name = 'Shimit Amin'), (SELECT id FROM movie WHERE title = 'Chak de! India'))
,((SELECT id FROM director WHERE name = 'Roman Polanski'), (SELECT id FROM movie WHERE title = 'Chinatown'))
,((SELECT id FROM director WHERE name = 'Fernando Meirelles'), (SELECT id FROM movie WHERE title = 'City of God'))
,((SELECT id FROM director WHERE name = 'Kátia Lund'), (SELECT id FROM movie WHERE title = 'City of God'))
,((SELECT id FROM director WHERE name = 'Orson Welles'), (SELECT id FROM movie WHERE title = 'Citizen Kane'))
,((SELECT id FROM director WHERE name = 'Charles Chaplin'), (SELECT id FROM movie WHERE title = 'City Lights'))
,((SELECT id FROM director WHERE name = 'Lee Unkrich'), (SELECT id FROM movie WHERE title = 'Coco'))
,((SELECT id FROM director WHERE name = 'Adrian Molina'), (SELECT id FROM movie WHERE title = 'Coco'))
,((SELECT id FROM director WHERE name = 'Oriol Paulo'), (SELECT id FROM movie WHERE title = 'The Invisible Guest'))
,((SELECT id FROM director WHERE name = 'Stuart Rosenberg'), (SELECT id FROM movie WHERE title = 'Cool Hand Luke'))
,((SELECT id FROM director WHERE name = 'Nitesh Tiwari'), (SELECT id FROM movie WHERE title = 'Dangal'))
,((SELECT id FROM director WHERE name = 'Wolfgang Petersen'), (SELECT id FROM movie WHERE title = 'Das Boot'))
,((SELECT id FROM director WHERE name = 'Florian Henckel von Donnersmarck'), (SELECT id FROM movie WHERE title = 'The Lives of Others'))
,((SELECT id FROM director WHERE name = 'Peter Weir'), (SELECT id FROM movie WHERE title = 'Dead Poets Society'))
,((SELECT id FROM director WHERE name = 'Oliver Hirschbiegel'), (SELECT id FROM movie WHERE title = 'Downfall'))
,((SELECT id FROM director WHERE name = 'Ingmar Bergman'), (SELECT id FROM movie WHERE title = 'The Seventh Seal'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'Dial M for Murder'))
,((SELECT id FROM director WHERE name = 'John McTiernan'), (SELECT id FROM movie WHERE title = 'Die Hard'))
,((SELECT id FROM director WHERE name = 'Quentin Tarantino'), (SELECT id FROM movie WHERE title = 'Django Unchained'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'Double Indemnity'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb'))
,((SELECT id FROM director WHERE name = 'Guillermo del Toro'), (SELECT id FROM movie WHERE title = 'Pan''s Labyrinth'))
,((SELECT id FROM director WHERE name = 'Juan José Campanella'), (SELECT id FROM movie WHERE title = 'The Secret in Their Eyes'))
,((SELECT id FROM director WHERE name = 'Yavuz Turgul'), (SELECT id FROM movie WHERE title = 'The Bandit'))
,((SELECT id FROM director WHERE name = 'Michel Gondry'), (SELECT id FROM movie WHERE title = 'Eternal Sunshine of the Spotless Mind'))
,((SELECT id FROM director WHERE name = 'Kar-Wai Wong'), (SELECT id FROM movie WHERE title = 'In the Mood for Love'))
,((SELECT id FROM director WHERE name = 'Joel Coen'), (SELECT id FROM movie WHERE title = 'Fargo'))
,((SELECT id FROM director WHERE name = 'Ethan Coen'), (SELECT id FROM movie WHERE title = 'Fargo'))
,((SELECT id FROM director WHERE name = 'David Fincher'), (SELECT id FROM movie WHERE title = 'Fight Club'))
,((SELECT id FROM director WHERE name = 'Andrew Stanton'), (SELECT id FROM movie WHERE title = 'Finding Nemo'))
,((SELECT id FROM director WHERE name = 'Lee Unkrich'), (SELECT id FROM movie WHERE title = 'Finding Nemo'))
,((SELECT id FROM director WHERE name = 'James Mangold'), (SELECT id FROM movie WHERE title = 'Ford v Ferrari'))
,((SELECT id FROM director WHERE name = 'Robert Zemeckis'), (SELECT id FROM movie WHERE title = 'Forrest Gump'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'Full Metal Jacket'))
,((SELECT id FROM director WHERE name = 'Anurag Kashyap'), (SELECT id FROM movie WHERE title = 'Gangs of Wasseypur'))
,((SELECT id FROM director WHERE name = 'Bong Joon Ho'), (SELECT id FROM movie WHERE title = 'Parasite'))
,((SELECT id FROM director WHERE name = 'Ridley Scott'), (SELECT id FROM movie WHERE title = 'Gladiator'))
,((SELECT id FROM director WHERE name = 'David Fincher'), (SELECT id FROM movie WHERE title = 'Gone Girl'))
,((SELECT id FROM director WHERE name = 'Victor Fleming'), (SELECT id FROM movie WHERE title = 'Gone with the Wind'))
,((SELECT id FROM director WHERE name = 'George Cukor'), (SELECT id FROM movie WHERE title = 'Gone with the Wind'))
,((SELECT id FROM director WHERE name = 'Sam Wood'), (SELECT id FROM movie WHERE title = 'Gone with the Wind'))
,((SELECT id FROM director WHERE name = 'Gus Van Sant'), (SELECT id FROM movie WHERE title = 'Good Will Hunting'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'Goodfellas'))
,((SELECT id FROM director WHERE name = 'Clint Eastwood'), (SELECT id FROM movie WHERE title = 'Gran Torino'))
,((SELECT id FROM director WHERE name = 'Peter Farrelly'), (SELECT id FROM movie WHERE title = 'Green Book'))
,((SELECT id FROM director WHERE name = 'Lasse Hallström'), (SELECT id FROM movie WHERE title = 'Hachi: A Dog''s Tale'))
,((SELECT id FROM director WHERE name = 'Mel Gibson'), (SELECT id FROM movie WHERE title = 'Hacksaw Ridge'))
,((SELECT id FROM director WHERE name = 'David Yates'), (SELECT id FROM movie WHERE title = 'Harry Potter and the Deathly Hallows: Part 2'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'Howl''s Moving Castle'))
,((SELECT id FROM director WHERE name = 'Michael Mann'), (SELECT id FROM movie WHERE title = 'Heat'))
,((SELECT id FROM director WHERE name = 'Isao Takahata'), (SELECT id FROM movie WHERE title = 'Grave of the Fireflies'))
,((SELECT id FROM director WHERE name = 'Terry George'), (SELECT id FROM movie WHERE title = 'Hotel Rwanda'))
,((SELECT id FROM director WHERE name = 'Dean DeBlois'), (SELECT id FROM movie WHERE title = 'How to Train Your Dragon'))
,((SELECT id FROM director WHERE name = 'Chris Sanders'), (SELECT id FROM movie WHERE title = 'How to Train Your Dragon'))
,((SELECT id FROM director WHERE name = 'Elem Klimov'), (SELECT id FROM movie WHERE title = 'Come and See'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'Ikiru'))
,((SELECT id FROM director WHERE name = 'Sergio Leone'), (SELECT id FROM movie WHERE title = 'The Good, the Bad and the Ugly'))
,((SELECT id FROM director WHERE name = 'Jim Sheridan'), (SELECT id FROM movie WHERE title = 'In the Name of the Father'))
,((SELECT id FROM director WHERE name = 'Denis Villeneuve'), (SELECT id FROM movie WHERE title = 'Incendies'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'Inception'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Indiana Jones and the Last Crusade'))
,((SELECT id FROM director WHERE name = 'Quentin Tarantino'), (SELECT id FROM movie WHERE title = 'Inglourious Basterds'))
,((SELECT id FROM director WHERE name = 'Pete Docter'), (SELECT id FROM movie WHERE title = 'Inside Out'))
,((SELECT id FROM director WHERE name = 'Ronnie Del Carmen'), (SELECT id FROM movie WHERE title = 'Inside Out'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'Interstellar'))
,((SELECT id FROM director WHERE name = 'Sean Penn'), (SELECT id FROM movie WHERE title = 'Into the Wild'))
,((SELECT id FROM director WHERE name = 'Olivier Nakache'), (SELECT id FROM movie WHERE title = 'The Intouchables'))
,((SELECT id FROM director WHERE name = 'Éric Toledano'), (SELECT id FROM movie WHERE title = 'The Intouchables'))
,((SELECT id FROM director WHERE name = 'Frank Capra'), (SELECT id FROM movie WHERE title = 'It Happened One Night'))
,((SELECT id FROM director WHERE name = 'Frank Capra'), (SELECT id FROM movie WHERE title = 'It''s a Wonderful Life'))
,((SELECT id FROM director WHERE name = 'Thomas Vinterberg'), (SELECT id FROM movie WHERE title = 'The Hunt'))
,((SELECT id FROM director WHERE name = 'Asghar Farhadi'), (SELECT id FROM movie WHERE title = 'A Separation'))
,((SELECT id FROM director WHERE name = 'Todd Phillips'), (SELECT id FROM movie WHERE title = 'Joker'))
,((SELECT id FROM director WHERE name = 'Stanley Kramer'), (SELECT id FROM movie WHERE title = 'Judgment at Nuremberg'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Jurassic Park'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'Nausicaä of the Valley of the Wind'))
,((SELECT id FROM director WHERE name = 'Quentin Tarantino'), (SELECT id FROM movie WHERE title = 'Kill Bill: Vol. 1'))
,((SELECT id FROM director WHERE name = 'Makoto Shinkai'), (SELECT id FROM movie WHERE title = 'Your Name.'))
,((SELECT id FROM director WHERE name = 'Sergio Pablos'), (SELECT id FROM movie WHERE title = 'Klaus'))
,((SELECT id FROM director WHERE name = 'Carlos Martínez López'), (SELECT id FROM movie WHERE title = 'Klaus'))
,((SELECT id FROM director WHERE name = 'Curtis Hanson'), (SELECT id FROM movie WHERE title = 'L.A. Confidential'))
,((SELECT id FROM director WHERE name = 'Mathieu Kassovitz'), (SELECT id FROM movie WHERE title = 'La Haine'))
,((SELECT id FROM director WHERE name = 'Carl Theodor Dreyer'), (SELECT id FROM movie WHERE title = 'The Passion of Joan of Arc'))
,((SELECT id FROM director WHERE name = 'Roberto Benigni'), (SELECT id FROM movie WHERE title = 'Life Is Beautiful'))
,((SELECT id FROM director WHERE name = 'Vittorio De Sica'), (SELECT id FROM movie WHERE title = 'Bicycle Thieves'))
,((SELECT id FROM director WHERE name = 'Ashutosh Gowariker'), (SELECT id FROM movie WHERE title = 'Lagaan: Once Upon a Time in India'))
,((SELECT id FROM director WHERE name = 'David Lean'), (SELECT id FROM movie WHERE title = 'Lawrence of Arabia'))
,((SELECT id FROM director WHERE name = 'Jean-Pierre Jeunet'), (SELECT id FROM movie WHERE title = 'Amélie'))
,((SELECT id FROM director WHERE name = 'Henri-Georges Clouzot'), (SELECT id FROM movie WHERE title = 'The Wages of Fear'))
,((SELECT id FROM director WHERE name = 'François Truffaut'), (SELECT id FROM movie WHERE title = 'The 400 Blows'))
,((SELECT id FROM director WHERE name = 'Terry Jones'), (SELECT id FROM movie WHERE title = 'Monty Python''s Life of Brian'))
,((SELECT id FROM director WHERE name = 'Greta Gerwig'), (SELECT id FROM movie WHERE title = 'Little Women'))
,((SELECT id FROM director WHERE name = 'Guy Ritchie'), (SELECT id FROM movie WHERE title = 'Lock, Stock and Two Smoking Barrels'))
,((SELECT id FROM director WHERE name = 'James Mangold'), (SELECT id FROM movie WHERE title = 'Logan'))
,((SELECT id FROM director WHERE name = 'Luc Besson'), (SELECT id FROM movie WHERE title = 'Léon: The Professional'))
,((SELECT id FROM director WHERE name = 'Fritz Lang'), (SELECT id FROM movie WHERE title = 'M'))
,((SELECT id FROM director WHERE name = 'George Miller'), (SELECT id FROM movie WHERE title = 'Mad Max: Fury Road'))
,((SELECT id FROM director WHERE name = 'Noah Baumbach'), (SELECT id FROM movie WHERE title = 'Marriage Story'))
,((SELECT id FROM director WHERE name = 'Adam Elliot'), (SELECT id FROM movie WHERE title = 'Mary and Max'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'Memento'))
,((SELECT id FROM director WHERE name = 'Fritz Lang'), (SELECT id FROM movie WHERE title = 'Metropolis'))
,((SELECT id FROM director WHERE name = 'Clint Eastwood'), (SELECT id FROM movie WHERE title = 'Million Dollar Baby'))
,((SELECT id FROM director WHERE name = 'Charles Chaplin'), (SELECT id FROM movie WHERE title = 'Modern Times'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'Princess Mononoke'))
,((SELECT id FROM director WHERE name = 'Pete Docter'), (SELECT id FROM movie WHERE title = 'Monsters, Inc.'))
,((SELECT id FROM director WHERE name = 'David Silverman'), (SELECT id FROM movie WHERE title = 'Monsters, Inc.'))
,((SELECT id FROM director WHERE name = 'Lee Unkrich'), (SELECT id FROM movie WHERE title = 'Monsters, Inc.'))
,((SELECT id FROM director WHERE name = 'Terry Gilliam'), (SELECT id FROM movie WHERE title = 'Monty Python and the Holy Grail'))
,((SELECT id FROM director WHERE name = 'Terry Jones'), (SELECT id FROM movie WHERE title = 'Monty Python and the Holy Grail'))
,((SELECT id FROM director WHERE name = 'Frank Capra'), (SELECT id FROM movie WHERE title = 'Mr. Smith Goes to Washington'))
,((SELECT id FROM director WHERE name = 'Sidney Lumet'), (SELECT id FROM movie WHERE title = 'Network'))
,((SELECT id FROM director WHERE name = 'Ethan Coen'), (SELECT id FROM movie WHERE title = 'No Country for Old Men'))
,((SELECT id FROM director WHERE name = 'Joel Coen'), (SELECT id FROM movie WHERE title = 'No Country for Old Men'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'North by Northwest'))
,((SELECT id FROM director WHERE name = 'Giuseppe Tornatore'), (SELECT id FROM movie WHERE title = 'Cinema Paradiso'))
,((SELECT id FROM director WHERE name = 'Chan-wook Park'), (SELECT id FROM movie WHERE title = 'Oldboy'))
,((SELECT id FROM director WHERE name = 'Elia Kazan'), (SELECT id FROM movie WHERE title = 'On the Waterfront'))
,((SELECT id FROM director WHERE name = 'Sergio Leone'), (SELECT id FROM movie WHERE title = 'Once Upon a Time in America'))
,((SELECT id FROM director WHERE name = 'Milos Forman'), (SELECT id FROM movie WHERE title = 'One Flew Over the Cuckoo''s Nest'))
,((SELECT id FROM director WHERE name = 'Rajkumar Hirani'), (SELECT id FROM movie WHERE title = 'PK'))
,((SELECT id FROM director WHERE name = 'Wim Wenders'), (SELECT id FROM movie WHERE title = 'Paris, Texas'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'Paths of Glory'))
,((SELECT id FROM director WHERE name = 'Sergio Leone'), (SELECT id FROM movie WHERE title = 'For a Few Dollars More'))
,((SELECT id FROM director WHERE name = 'Ingmar Bergman'), (SELECT id FROM movie WHERE title = 'Persona'))
,((SELECT id FROM director WHERE name = 'Oliver Stone'), (SELECT id FROM movie WHERE title = 'Platoon'))
,((SELECT id FROM director WHERE name = 'Denis Villeneuve'), (SELECT id FROM movie WHERE title = 'Prisoners'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'Psycho'))
,((SELECT id FROM director WHERE name = 'Quentin Tarantino'), (SELECT id FROM movie WHERE title = 'Pulp Fiction'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'Raging Bull'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Raiders of the Lost Ark'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'Ran'))
,((SELECT id FROM director WHERE name = 'Rakeysh Omprakash Mehra'), (SELECT id FROM movie WHERE title = 'Rang De Basanti'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'Rashomon'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'Rear Window'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'Rebecca'))
,((SELECT id FROM director WHERE name = 'Damián Szifron'), (SELECT id FROM movie WHERE title = 'Wild Tales'))
,((SELECT id FROM director WHERE name = 'Darren Aronofsky'), (SELECT id FROM movie WHERE title = 'Requiem for a Dream'))
,((SELECT id FROM director WHERE name = 'Quentin Tarantino'), (SELECT id FROM movie WHERE title = 'Reservoir Dogs'))
,((SELECT id FROM director WHERE name = 'John G. Avildsen'), (SELECT id FROM movie WHERE title = 'Rocky'))
,((SELECT id FROM director WHERE name = 'Lenny Abrahamson'), (SELECT id FROM movie WHERE title = 'Room'))
,((SELECT id FROM director WHERE name = 'Ron Howard'), (SELECT id FROM movie WHERE title = 'Rush'))
,((SELECT id FROM director WHERE name = 'Bong Joon Ho'), (SELECT id FROM movie WHERE title = 'Memories of Murder'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Saving Private Ryan'))
,((SELECT id FROM director WHERE name = 'Brian De Palma'), (SELECT id FROM movie WHERE title = 'Scarface'))
,((SELECT id FROM director WHERE name = 'Steven Spielberg'), (SELECT id FROM movie WHERE title = 'Schindler''s List'))
,((SELECT id FROM director WHERE name = 'David Fincher'), (SELECT id FROM movie WHERE title = 'Se7en'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'Spirited Away'))
,((SELECT id FROM director WHERE name = 'Masaki Kobayashi'), (SELECT id FROM movie WHERE title = 'Harakiri'))
,((SELECT id FROM director WHERE name = 'Buster Keaton'), (SELECT id FROM movie WHERE title = 'Sherlock Jr.'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'Seven Samurai'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'Shutter Island'))
,((SELECT id FROM director WHERE name = 'Stanley Donen'), (SELECT id FROM movie WHERE title = 'Singin'' in the Rain'))
,((SELECT id FROM director WHERE name = 'Gene Kelly'), (SELECT id FROM movie WHERE title = 'Singin'' in the Rain'))
,((SELECT id FROM director WHERE name = 'Ingmar Bergman'), (SELECT id FROM movie WHERE title = 'Wild Strawberries'))
,((SELECT id FROM director WHERE name = 'Guy Ritchie'), (SELECT id FROM movie WHERE title = 'Snatch'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'Some Like It Hot'))
,((SELECT id FROM director WHERE name = 'Bob Persichetti'), (SELECT id FROM movie WHERE title = 'Spider-Man: Into the Spider-Verse'))
,((SELECT id FROM director WHERE name = 'Peter Ramsey'), (SELECT id FROM movie WHERE title = 'Spider-Man: Into the Spider-Verse'))
,((SELECT id FROM director WHERE name = 'Rodney Rothman'), (SELECT id FROM movie WHERE title = 'Spider-Man: Into the Spider-Verse'))
,((SELECT id FROM director WHERE name = 'Tom McCarthy'), (SELECT id FROM movie WHERE title = 'Spotlight'))
,((SELECT id FROM director WHERE name = 'Andrei Tarkovsky'), (SELECT id FROM movie WHERE title = 'Stalker'))
,((SELECT id FROM director WHERE name = 'Rob Reiner'), (SELECT id FROM movie WHERE title = 'Stand by Me'))
,((SELECT id FROM director WHERE name = 'George Lucas'), (SELECT id FROM movie WHERE title = 'Star Wars: Episode IV - A New Hope'))
,((SELECT id FROM director WHERE name = 'Irvin Kershner'), (SELECT id FROM movie WHERE title = 'Star Wars: Episode V - The Empire Strikes Back'))
,((SELECT id FROM director WHERE name = 'Richard Marquand'), (SELECT id FROM movie WHERE title = 'Star Wars: Episode VI - Return of the Jedi'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'Sunset Blvd.'))
,((SELECT id FROM director WHERE name = 'Aamir Khan'), (SELECT id FROM movie WHERE title = 'Like Stars on Earth'))
,((SELECT id FROM director WHERE name = 'Amole Gupte'), (SELECT id FROM movie WHERE title = 'Like Stars on Earth'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'Taxi Driver'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'High and Low'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'Castle in the Sky'))
,((SELECT id FROM director WHERE name = 'James Cameron'), (SELECT id FROM movie WHERE title = 'Terminator 2: Judgment Day'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'The Apartment'))
,((SELECT id FROM director WHERE name = 'Joel Coen'), (SELECT id FROM movie WHERE title = 'The Big Lebowski'))
,((SELECT id FROM director WHERE name = 'Ethan Coen'), (SELECT id FROM movie WHERE title = 'The Big Lebowski'))
,((SELECT id FROM director WHERE name = 'David Lean'), (SELECT id FROM movie WHERE title = 'The Bridge on the River Kwai'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'The Dark Knight'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'The Dark Knight Rises'))
,((SELECT id FROM director WHERE name = 'Michael Cimino'), (SELECT id FROM movie WHERE title = 'The Deer Hunter'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'The Departed'))
,((SELECT id FROM director WHERE name = 'David Lynch'), (SELECT id FROM movie WHERE title = 'The Elephant Man'))
,((SELECT id FROM director WHERE name = 'Clyde Bruckman'), (SELECT id FROM movie WHERE title = 'The General'))
,((SELECT id FROM director WHERE name = 'Buster Keaton'), (SELECT id FROM movie WHERE title = 'The General'))
,((SELECT id FROM director WHERE name = 'Francis Ford Coppola'), (SELECT id FROM movie WHERE title = 'The Godfather'))
,((SELECT id FROM director WHERE name = 'Francis Ford Coppola'), (SELECT id FROM movie WHERE title = 'The Godfather: Part II'))
,((SELECT id FROM director WHERE name = 'Charles Chaplin'), (SELECT id FROM movie WHERE title = 'The Gold Rush'))
,((SELECT id FROM director WHERE name = 'Wes Anderson'), (SELECT id FROM movie WHERE title = 'The Grand Budapest Hotel'))
,((SELECT id FROM director WHERE name = 'Charles Chaplin'), (SELECT id FROM movie WHERE title = 'The Great Dictator'))
,((SELECT id FROM director WHERE name = 'John Sturges'), (SELECT id FROM movie WHERE title = 'The Great Escape'))
,((SELECT id FROM director WHERE name = 'Frank Darabont'), (SELECT id FROM movie WHERE title = 'The Green Mile'))
,((SELECT id FROM director WHERE name = 'Tate Taylor'), (SELECT id FROM movie WHERE title = 'The Help'))
,((SELECT id FROM director WHERE name = 'Charles Chaplin'), (SELECT id FROM movie WHERE title = 'The Kid'))
,((SELECT id FROM director WHERE name = 'Roger Allers'), (SELECT id FROM movie WHERE title = 'The Lion King'))
,((SELECT id FROM director WHERE name = 'Rob Minkoff'), (SELECT id FROM movie WHERE title = 'The Lion King'))
,((SELECT id FROM director WHERE name = 'Peter Jackson'), (SELECT id FROM movie WHERE title = 'The Lord of the Rings: The Fellowship of the Ring'))
,((SELECT id FROM director WHERE name = 'Peter Jackson'), (SELECT id FROM movie WHERE title = 'The Lord of the Rings: The Return of the King'))
,((SELECT id FROM director WHERE name = 'Peter Jackson'), (SELECT id FROM movie WHERE title = 'The Lord of the Rings: The Two Towers'))
,((SELECT id FROM director WHERE name = 'Lana Wachowski'), (SELECT id FROM movie WHERE title = 'The Matrix'))
,((SELECT id FROM director WHERE name = 'Lilly Wachowski'), (SELECT id FROM movie WHERE title = 'The Matrix'))
,((SELECT id FROM director WHERE name = 'Roman Polanski'), (SELECT id FROM movie WHERE title = 'The Pianist'))
,((SELECT id FROM director WHERE name = 'Christopher Nolan'), (SELECT id FROM movie WHERE title = 'The Prestige'))
,((SELECT id FROM director WHERE name = 'Rob Reiner'), (SELECT id FROM movie WHERE title = 'The Princess Bride'))
,((SELECT id FROM director WHERE name = 'Michael Powell'), (SELECT id FROM movie WHERE title = 'The Red Shoes'))
,((SELECT id FROM director WHERE name = 'Emeric Pressburger'), (SELECT id FROM movie WHERE title = 'The Red Shoes'))
,((SELECT id FROM director WHERE name = 'Frank Darabont'), (SELECT id FROM movie WHERE title = 'The Shawshank Redemption'))
,((SELECT id FROM director WHERE name = 'Stanley Kubrick'), (SELECT id FROM movie WHERE title = 'The Shining'))
,((SELECT id FROM director WHERE name = 'Jonathan Demme'), (SELECT id FROM movie WHERE title = 'The Silence of the Lambs'))
,((SELECT id FROM director WHERE name = 'M. Night Shyamalan'), (SELECT id FROM movie WHERE title = 'The Sixth Sense'))
,((SELECT id FROM director WHERE name = 'George Roy Hill'), (SELECT id FROM movie WHERE title = 'The Sting'))
,((SELECT id FROM director WHERE name = 'James Cameron'), (SELECT id FROM movie WHERE title = 'The Terminator'))
,((SELECT id FROM director WHERE name = 'John Carpenter'), (SELECT id FROM movie WHERE title = 'The Thing'))
,((SELECT id FROM director WHERE name = 'Carol Reed'), (SELECT id FROM movie WHERE title = 'The Third Man'))
,((SELECT id FROM director WHERE name = 'John Huston'), (SELECT id FROM movie WHERE title = 'The Treasure of the Sierra Madre'))
,((SELECT id FROM director WHERE name = 'Peter Weir'), (SELECT id FROM movie WHERE title = 'The Truman Show'))
,((SELECT id FROM director WHERE name = 'Bryan Singer'), (SELECT id FROM movie WHERE title = 'The Usual Suspects'))
,((SELECT id FROM director WHERE name = 'Martin Scorsese'), (SELECT id FROM movie WHERE title = 'The Wolf of Wall Street'))
,((SELECT id FROM director WHERE name = 'Paul Thomas Anderson'), (SELECT id FROM movie WHERE title = 'There Will Be Blood'))
,((SELECT id FROM director WHERE name = 'Martin McDonagh'), (SELECT id FROM movie WHERE title = 'Three Billboards Outside Ebbing, Missouri'))
,((SELECT id FROM director WHERE name = 'Robert Mulligan'), (SELECT id FROM movie WHERE title = 'To Kill a Mockingbird'))
,((SELECT id FROM director WHERE name = 'Hayao Miyazaki'), (SELECT id FROM movie WHERE title = 'My Neighbor Totoro'))
,((SELECT id FROM director WHERE name = 'John Lasseter'), (SELECT id FROM movie WHERE title = 'Toy Story'))
,((SELECT id FROM director WHERE name = 'Lee Unkrich'), (SELECT id FROM movie WHERE title = 'Toy Story 3'))
,((SELECT id FROM director WHERE name = 'Danny Boyle'), (SELECT id FROM movie WHERE title = 'Trainspotting'))
,((SELECT id FROM director WHERE name = 'Yasujirô Ozu'), (SELECT id FROM movie WHERE title = 'Tokyo Story'))
,((SELECT id FROM director WHERE name = 'Clint Eastwood'), (SELECT id FROM movie WHERE title = 'Unforgiven'))
,((SELECT id FROM director WHERE name = 'Pete Docter'), (SELECT id FROM movie WHERE title = 'Up'))
,((SELECT id FROM director WHERE name = 'Bob Peterson'), (SELECT id FROM movie WHERE title = 'Up'))
,((SELECT id FROM director WHERE name = 'James McTeigue'), (SELECT id FROM movie WHERE title = 'V for Vendetta'))
,((SELECT id FROM director WHERE name = 'Alfred Hitchcock'), (SELECT id FROM movie WHERE title = 'Vertigo'))
,((SELECT id FROM director WHERE name = 'Andrew Stanton'), (SELECT id FROM movie WHERE title = 'WALL·E'))
,((SELECT id FROM director WHERE name = 'Gavin O''Connor'), (SELECT id FROM movie WHERE title = 'Warrior'))
,((SELECT id FROM director WHERE name = 'Damien Chazelle'), (SELECT id FROM movie WHERE title = 'Whiplash'))
,((SELECT id FROM director WHERE name = 'Raoul Walsh'), (SELECT id FROM movie WHERE title = 'White Heat'))
,((SELECT id FROM director WHERE name = 'Billy Wilder'), (SELECT id FROM movie WHERE title = 'Witness for the Prosecution'))
,((SELECT id FROM director WHERE name = 'Akira Kurosawa'), (SELECT id FROM movie WHERE title = 'Yojimbo'));