INSERT INTO director(name) VALUES
('Aamir Khan')
,('Adam Elliot')
,('Adrian Molina')
,('Akira Kurosawa')
,('Alejandro G. Iñárritu')
,('Alfred Hitchcock')
,('Amole Gupte')
,('Andrei Tarkovsky')
,('Andrew Stanton')
,('Anthony Russo')
,('Anurag Kashyap')
,('Asghar Farhadi')
,('Ashutosh Gowariker')
,('Billy Wilder')
,('Bob Persichetti')
,('Bob Peterson')
,('Bong Joon Ho')
,('Brian De Palma')
,('Bryan Singer')
,('Buster Keaton')
,('Carl Theodor Dreyer')
,('Carlos Martínez López')
,('Carol Reed')
,('Chan-wook Park')
,('Charles Chaplin')
,('Chris Sanders')
,('Christopher Nolan')
,('Clint Eastwood')
,('Clyde Bruckman')
,('Curtis Hanson')
,('Damien Chazelle')
,('Damián Szifron')
,('Danny Boyle')
,('Darren Aronofsky')
,('David Fincher')
,('David Lean')
,('David Lynch')
,('David Silverman')
,('David Yates')
,('Dean DeBlois')
,('Denis Villeneuve')
,('Elem Klimov')
,('Elia Kazan')
,('Emeric Pressburger')
,('Ethan Coen')
,('Fernando Meirelles')
,('Florian Henckel von Donnersmarck')
,('Francis Ford Coppola')
,('Frank Capra')
,('Frank Darabont')
,('François Truffaut')
,('Fritz Lang')
,('Gavin O''Connor')
,('Gene Kelly')
,('George Cukor')
,('George Lucas')
,('George Miller')
,('George Roy Hill')
,('Giuseppe Tornatore')
,('Greta Gerwig')
,('Guillermo del Toro')
,('Gus Van Sant')
,('Guy Ritchie')
,('Hayao Miyazaki')
,('Henri-Georges Clouzot')
,('Ingmar Bergman')
,('Irvin Kershner')
,('Isao Takahata')
,('James Cameron')
,('James Mangold')
,('James McTeigue')
,('Jean-Pierre Jeunet')
,('Jim Sheridan')
,('Joe Russo')
,('Joel Coen')
,('John Carpenter')
,('John G. Avildsen')
,('John Huston')
,('John Lasseter')
,('John McTiernan')
,('John Musker')
,('John Sturges')
,('Jonathan Demme')
,('Joseph L. Mankiewicz')
,('Juan José Campanella')
,('Kar-Wai Wong')
,('Katsuhiro Ôtomo')
,('Kátia Lund')
,('Lana Wachowski')
,('Lasse Hallström')
,('Lee Unkrich')
,('Lenny Abrahamson')
,('Lilly Wachowski')
,('Luc Besson')
,('M. Night Shyamalan')
,('Majid Majidi')
,('Makoto Shinkai')
,('Martin McDonagh')
,('Martin Scorsese')
,('Masaki Kobayashi')
,('Mathieu Kassovitz')
,('Mel Gibson')
,('Michael Cimino')
,('Michael Curtiz')
,('Michael Mann')
,('Michael Powell')
,('Michel Gondry')
,('Milos Forman')
,('Nadine Labaki')
,('Nitesh Tiwari')
,('Noah Baumbach')
,('Oliver Hirschbiegel')
,('Oliver Stone')
,('Olivier Nakache')
,('Oriol Paulo')
,('Orson Welles')
,('Paul Thomas Anderson')
,('Pete Docter')
,('Peter Farrelly')
,('Peter Jackson')
,('Peter Ramsey')
,('Peter Weir')
,('Quentin Tarantino')
,('Rajkumar Hirani')
,('Rakeysh Omprakash Mehra')
,('Raoul Walsh')
,('Richard Linklater')
,('Richard Marquand')
,('Ridley Scott')
,('Rob Minkoff')
,('Rob Reiner')
,('Robert Mulligan')
,('Robert Zemeckis')
,('Roberto Benigni')
,('Rodney Rothman')
,('Roger Allers')
,('Roman Polanski')
,('Ron Clements')
,('Ron Howard')
,('Ronnie Del Carmen')
,('Sam Mendes')
,('Sam Wood')
,('Sean Penn')
,('Sergio Leone')
,('Sergio Pablos')
,('Shimit Amin')
,('Sidney Lumet')
,('Sriram Raghavan')
,('Stanley Donen')
,('Stanley Kramer')
,('Stanley Kubrick')
,('Steve McQueen')
,('Steven Spielberg')
,('Stuart Rosenberg')
,('Tate Taylor')
,('Terry George')
,('Terry Gilliam')
,('Terry Jones')
,('Thomas Vinterberg')
,('Todd Phillips')
,('Tom McCarthy')
,('Tony Kaye')
,('Victor Fleming')
,('Vittorio De Sica')
,('Wes Anderson')
,('William Wyler')
,('Wim Wenders')
,('Wolfgang Petersen')
,('Yasujirô Ozu')
,('Yavuz Turgul')
,('Çagan Irmak')
,('Éric Toledano');